version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: flashcards-db
    environment:
      POSTGRES_DB: flashcards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Port removed for security - access db through Docker network only
    # For local debugging, uncomment: ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flashcards-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flashcards-backend
    ports:
      - "8000:8000"
    environment:
      APP_NAME: smart_flashcards
      DATABASE_URL: postgresql+psycopg://postgres:${POSTGRES_PASSWORD:-devpassword123}@db:5432/flashcards
      JWT_ALG: HS256
      JWT_SECRET: ${JWT_SECRET:-dev-secret-change-in-production}
      CORS_ORIGINS: '["http://localhost:3000", "http://frontend:3000"]'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - flashcards-network
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend/flashcards-fe
      dockerfile: Dockerfile
    container_name: flashcards-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - flashcards-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  flashcards-network:
    driver: bridge
