"""Added study session and metrics models

Revision ID: 377e1dad6030
Revises: 72a0479cbc1e
Create Date: 2025-10-07 21:49:47.656657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377e1dad6030'
down_revision: Union[str, Sequence[str], None] = '72a0479cbc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('cards_studied', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('average_time_per_card', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_id'), 'study_sessions', ['id'], unique=False)
    op.create_table('card_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('time_taken_ms', sa.Integer(), nullable=False),
    sa.Column('typed_chars', sa.Integer(), nullable=True),
    sa.Column('backspace_count', sa.Integer(), nullable=True),
    sa.Column('hesitation_detected', sa.Boolean(), nullable=True),
    sa.Column('typing_speed_cpm', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('session_position', sa.Integer(), nullable=True),
    sa.Column('previous_card_correct', sa.Boolean(), nullable=True),
    sa.Column('self_rated_difficulty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_metrics_id'), 'card_metrics', ['id'], unique=False)
    op.add_column('cards', sa.Column('accuracy_rate', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('avg_response_time', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('typo_count', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('last_reviewed', sa.DateTime(), nullable=True))
    op.add_column('cards', sa.Column('proficiency_score', sa.Float(), nullable=True))
    op.add_column('cards', sa.Column('times_seen', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'study_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'session_id')
    op.drop_column('cards', 'times_seen')
    op.drop_column('cards', 'proficiency_score')
    op.drop_column('cards', 'last_reviewed')
    op.drop_column('cards', 'typo_count')
    op.drop_column('cards', 'avg_response_time')
    op.drop_column('cards', 'accuracy_rate')
    op.drop_index(op.f('ix_card_metrics_id'), table_name='card_metrics')
    op.drop_table('card_metrics')
    op.drop_index(op.f('ix_study_sessions_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    # ### end Alembic commands ###
